# Generated by Django 2.2.4 on 2021-02-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('birthdayMonth', models.CharField(max_length=30, null=True)),
                ('birthdayDay', models.IntegerField(null=True)),
                ('birthdayYear', models.IntegerField(null=True)),
                ('emailAddress', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('confirmPassword', models.CharField(max_length=255)),
                ('profilePic', models.ImageField(null=True, upload_to='submittedProfilePicImages/', verbose_name='')),
                ('profileInfo', models.CharField(default='', max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
