# Generated by Django 2.2.4 on 2021-02-04 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', to='wallApp.User'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('likeMessageCount', models.IntegerField(default=0)),
                ('likeMessageCountMinusDisplayNames', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='wallApp.User')),
                ('userLikes', models.ManyToManyField(related_name='theLiker', to='wallApp.User')),
                ('userReceivesPost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postRecipient', to='wallApp.User')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendingRequest', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('receiverOfFriendRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallApp.User')),
                ('senderOfFriendRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loggedInUser', to='wallApp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wallApp.Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wallApp.User')),
                ('userReceivesComment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentee', to='wallApp.User')),
            ],
        ),
    ]
