# Generated by Django 2.2.4 on 2021-03-01 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='comment',
        ),
    ]
