# Generated by Django 2.2.4 on 2021-02-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0002_auto_20210221_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userCheckBox',
            field=models.BooleanField(default='0'),
        ),
    ]
