# Generated by Django 2.2.4 on 2021-02-04 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0002_auto_20210204_1900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
