# Generated by Django 2.2.4 on 2021-02-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0003_delete_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='friendship', to='wallApp.User'),
        ),
    ]
