# Generated by Django 2.2.4 on 2021-03-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0003_notification_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='notification',
            field=models.IntegerField(default='0'),
        ),
    ]
