# Generated by Django 2.2.4 on 2021-03-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0004_message_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='friends',
            field=models.ManyToManyField(related_name='friendship', to='wallApp.Notification'),
        ),
    ]
