# Generated by Django 2.2.4 on 2021-03-30 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0005_notification_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='friendRequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userID', to='wallApp.User'),
        ),
    ]
