# Generated by Django 2.2.4 on 2020-11-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0006_auto_20201020_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePhoto',
            field=models.FileField(null=True, upload_to='media/', verbose_name=''),
        ),
    ]
