# Generated by Django 2.2.4 on 2021-03-30 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0006_notification_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='friends',
        ),
    ]
