# Generated by Django 2.2.4 on 2020-11-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0007_auto_20201123_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profilePhoto',
            new_name='profilePic',
        ),
    ]
