# Generated by Django 2.2.4 on 2021-04-02 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0008_auto_20210330_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='commenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userComments', to='wallApp.User'),
        ),
    ]
