# Generated by Django 2.2.4 on 2020-11-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0008_auto_20201124_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.FileField(null=True, upload_to='submittedProfilePicImages/', verbose_name=''),
        ),
    ]
