# Generated by Django 2.2.4 on 2021-04-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0009_notification_commenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='hover',
            field=models.IntegerField(default='0'),
        ),
    ]
