# Generated by Django 2.2.4 on 2020-11-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0009_auto_20201129_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(null=True, upload_to='submittedProfilePicImages/', verbose_name=''),
        ),
    ]
