# Generated by Django 2.2.4 on 2020-12-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0010_auto_20201129_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileInfo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
