# Generated by Django 2.2.4 on 2021-01-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0011_user_profileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='wallOfPosts',
            field=models.ManyToManyField(related_name='postedMessages', to='wallApp.User'),
        ),
    ]
