# Generated by Django 2.2.4 on 2021-01-13 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0012_message_wallofposts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='wallOfPosts',
        ),
        migrations.AddField(
            model_name='message',
            name='userReceivesPost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallOfMessage', to='wallApp.User'),
        ),
    ]
