# Generated by Django 2.2.4 on 2021-01-14 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0013_auto_20210113_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='userReceivesComment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentee', to='wallApp.User'),
        ),
    ]
