# Generated by Django 2.2.4 on 2021-01-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0014_comment_userreceivescomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='messageLiked',
            field=models.ManyToManyField(related_name='likedMessage', to='wallApp.User'),
        ),
    ]
