# Generated by Django 2.2.4 on 2021-01-15 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0015_message_messageliked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='messageLiked',
        ),
        migrations.AddField(
            model_name='message',
            name='likedMessage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messageLiked', to='wallApp.User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='userLikes',
            field=models.ManyToManyField(related_name='theLiker', to='wallApp.User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='userReceivesPost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postRecipient', to='wallApp.User'),
        ),
    ]
