# Generated by Django 2.2.4 on 2021-01-15 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0017_auto_20210115_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='likedMessageCount',
            new_name='likeMessageCount',
        ),
    ]
