# Generated by Django 2.2.4 on 2021-01-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0018_auto_20210115_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='likeMessageCountMinusDisplayNames',
            field=models.IntegerField(default=0),
        ),
    ]
