# Generated by Django 2.2.4 on 2021-01-19 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0019_message_likemessagecountminusdisplaynames'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(default=True, related_name='listOfFriends', to='wallApp.User')),
                ('userAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendList', to='wallApp.User')),
            ],
        ),
    ]
