# Generated by Django 2.2.4 on 2021-01-19 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0021_auto_20210119_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendlist',
            old_name='loggedInUser',
            new_name='user',
        ),
        migrations.AddField(
            model_name='friendlist',
            name='friendRequestRecipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friendRequestRecipient', to='wallApp.User'),
        ),
    ]
