# Generated by Django 2.2.4 on 2021-01-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0022_auto_20210119_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', to='wallApp.User'),
        ),
        migrations.DeleteModel(
            name='FriendList',
        ),
    ]
